steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: 'backend-app-xitomate'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend-app-xitomate', '.']
images:
- 'gcr.io/$PROJECT_ID/backend-app-xitomate'
