steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: backend-app-xitomate
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/backend-app-xitomate'
    - '-f'
    - 'Dockerfile'
    - '.'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - backend-app-xitomate
    - --image=gcr.io/$PROJECT_ID/backend-app-xitomate
    - --region=us-central1
    - --platform=managed
    - --quiet
    - --allow-unauthenticated
images:
- 'gcr.io/$PROJECT_ID/backend-app-xitomate'
