steps:
- name: 'gcr.io/cloud-builders/docker'
  dir: '.'
  args: ['build', '-t', 'gcr.io/inlaid-fire-458421-e0/backend-app-xitomate', '.']
images:
- 'gcr.io/inlaid-fire-458421-e0/backend-app-xitomate' 