steps:
- name: 'gcr.io/cloud-builders/docker'

    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/backend-app-xitomate'
    - '-f'
    - 'Dockerfile'
    - '.'

images:
- 'gcr.io/$PROJECT_ID/backend-app-xitomate'
